server:
  port: 7529 # ???????????????????

spring:
  mvc:
    pathmatch:
      # ? ????????? Swagger ??????
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ????????? MySQL ???
    url: jdbc:mysql://localhost:3306/tengyun_api?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: xjpnmsl111 # ? ?????????????

mybatis-plus:
  configuration:
    # ??????? SQL ?????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # ?????????? (??? user_name -> ??? userName)
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # ???????????
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
dubbo:
  application:
    name: tengyun-api-backend # ? Nacos ???????
  protocol:
    name: dubbo # ??? dubbo ????????
    port: -1 # ?? -1 ???????????????? 20880?
  registry:
    id: nacos-registry
    address: nacos://localhost:8848 # ? Nacos ?????
# Knife4j ????
knife4j:
  enable: true
  openapi:
    title: "?? API ??????"
    description: "?? Spring Boot 3 ???? API ????"
    version: 1.0.0

app:
  text-repair:
    run-on-startup: false
    dry-run-on-startup: true
